### ISSUE TITLE
[BUG] Unable to update "pates au pesto"

### ISSUE THREAD

**Issue by juvarlet** [juvarlet/a_table#54]
Traceback (most recent call last):
  File "/home/jv/Documents/gitRepos/a_table/edit_recipe.py", line 220, in on_btn_confirm_changes_clicked
    if ing_item.getUID() == ing_item_id:
AttributeError: 'NoneType' object has no attribute 'getUID'
Traceback (most recent call last):
  File "/home/jv/Documents/gitRepos/a_table/edit_recipe.py", line 280, in on_confirm_recipe
    ing_dict[ing_item.lbl_ing_name.text()] = [float(ing_item.lbl_ing_qty.text()), ing_item.lbl_ing_qty_unit.text()]
AttributeError: 'NoneType' object has no attribute 'lbl_ing_qty'

**Comment by juvarlet** [comment]
Fixed by removing "findChild" in lW ingredientItem 
commit on ju_branch : 4f9c7675de1963d3a863bced4988e56ce35bf802
